<a href="https://colab.research.google.com/github/Thanchanya309/PythonDataViz2026/blob/main/HW7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW7 สร้างตารางใหม่ ที่ค่าใน ```sex``` เป็น missing ทั้งหมด  
- สรุปว่าทำไม record นั้นๆถึงเป็น missing

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

path = '/content/drive/MyDrive/Basic Program'

In [4]:
covid_file_path = os.path.join(path,'confirmed-cases.csv')
print(covid_file_path)

/content/drive/MyDrive/Basic Program/confirmed-cases.csv

In [5]:
a = path + 'confirmed-cases.csv'
print(a)

/content/drive/MyDrive/Basic Programconfirmed-cases.csv

In [6]:
import pandas as pd

In [7]:
data_covid = pd.read_csv(covid_file_path)
data_covid

/tmp/ipykernel_2680/318669438.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(covid_file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,NaN,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839770,839771,12/8/2021,11/8/2021,ชาย,47.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN

In [8]:
data_covid.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [9]:
data_covid['sex'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
839766    False
839767    False
839768    False
839769    False
839770    False
Name: sex, Length: 839771, dtype: bool

In [10]:
missing_sex = data_covid[data_covid['sex'].isnull()]
missing_sex

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
4397,4398,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4398,4399,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4399,4400,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4400,4401,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4401,4402,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
...,...,...,...,...,...,...,...,...,...,...,...
838332,838333,12/8/2021,11/8/2021,NaN,3.0,ปี,Thailand,กรุงเทพมหานคร,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,กรุงเทพมหานคร,บางคอแหลม
839174,839175,12/8/2021,11/8/2021,NaN,47.0,ปี,Thailand,กรุงเทพมหานคร,ระบุไม่ได้,กรุงเทพมหานคร,บางคอแหลม
839304,839305,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,กรุงเทพมหานคร,ระบุไม่ได้,NaN,NaN
839396,839397,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,นครราชสีมา,ทัณฑสถาน/เรือนจำ,นครราชสีมา,NaN
839397,839398,12/8/2021,11/8/2021,NaN,NaN,NaN,NaN,นครราชสีมา,ทัณฑสถาน/เรือนจำ,นครราชสีมา,NaN

In [11]:
missing_sex.groupby('nationality').describe()

                    No.                                                     \
                  count           mean            std       min        25%
nationality
Australia           1.0   28064.000000            NaN   28064.0   28064.00
Burma            1616.0    9419.358911   13598.566273    4398.0    4801.75
Burmese          1383.0  255454.475054  178791.318645  120567.0  141873.50
Cambodia          115.0   26802.669565   30905.712127    6544.0    7033.50
Cambodian          99.0  316970.050505  279781.660775  120554.0  124617.00
Cameroon            1.0   28059.000000            NaN   28059.0   28059.00
China               2.0   39781.500000   16308.003695   28250.0   34015.75
Chinese             2.0  383704.500000  299451.943658  171960.0  277832.25
Cote D'Ivoire       1.0   28101.000000            NaN   28101.0   28101.00
Guinean            19.0  120573.526316      16.833724  120552.0  120561.50
India               9.0   28159.555556      82.813210   28024.0   28110.00
Indian              3.0  164508.333333   58030.543176  126363.0  131117.00
Indonesian          1.0  248552.000000            NaN  248552.0  248552.00
Iraq                1.0   28196.000000            NaN   28196.0   28196.00
Japan               2.0   50664.000000     820.243866   50084.0   50374.00
Korea, South        1.0   28107.000000            NaN   28107.0   28107.00
Laos               46.0   50308.217391   30778.870280   27984.0   28113.25
Laotian / Lao      88.0  155929.784091   86179.246054  120571.0  124620.50
Malaysia            1.0   28094.000000            NaN   28094.0   28094.00
Malian              1.0  120588.000000            NaN  120588.0  120588.00
Netherlands         1.0   28031.000000            NaN   28031.0   28031.00
Nigeria             3.0   28127.666667      91.522311   28022.0   28100.50
Nigerian            1.0  177040.000000            NaN  177040.0  177040.00
Pakistan            1.0   28207.000000            NaN   28207.0   28207.00
Palestinian         1.0   28145.000000            NaN   28145.0   28145.00
Romania             1.0   28030.000000            NaN   28030.0   28030.00
Russia              1.0   28143.000000            NaN   28143.0   28143.00
Singaporean         1.0  162408.000000            NaN  162408.0  162408.00
Sri Lanka           1.0   28108.000000            NaN   28108.0   28108.00
Syria               1.0   28186.000000            NaN   28186.0   28186.00
Taiwanese           2.0  169797.000000   10233.249337  162561.0  166179.00
Thai              116.0  706244.724138    1241.897914  693631.0  706082.75
Thailand        13263.0  405670.366961  242166.696933    6268.0  168617.50
Timor-Leste         1.0  124928.000000            NaN  124928.0  124928.00
United Kingdom      3.0   39506.000000   19771.593031   27995.0   28091.00
Vietnam            11.0   28087.272727      71.178776   28048.0   28054.50
Yemen               1.0   28095.000000            NaN   28095.0   28095.00
burmese             7.0  240404.142857  115300.897255  196821.0  196822.50
ไม่มีสัญชาติ        2.0   28155.000000      96.166522   28087.0   28121.00


                     50%        75%       max
nationality
Australia        28064.0   28064.00   28064.0
Burma             5227.5    5661.25  108198.0
Burmese         164500.0  277338.50  830633.0
Cambodia          7160.0   28189.50  108201.0
Cambodian       124972.0  623669.00  830563.0
Cameroon         28059.0   28059.00   28059.0
China            39781.5   45547.25   51313.0
Chinese         383704.5  489576.75  595449.0
Cote D'Ivoire    28101.0   28101.00   28101.0
Guinean         120568.0  120588.50  120600.0
India            28208.0   28211.00   28244.0
Indian          135871.0  183581.00  231291.0
Indonesian      248552.0  248552.00  248552.0
Iraq             28196.0   28196.00   28196.0
Japan            50664.0   50954.00   51244.0
Korea, South     28107.0   28107.00   28107.0
Laos             28222.5   88576.75  108197.0
Laotian / Lao   124692.5  125409.25  607945.0
Malaysia         28094.0   28094.00   28094.0
Malian          120588.0  120588.00  120588.0
Netherlands      28031.0   28031.00   28031.0
Nigeria          28179.0   28180.50   28182.0
Nigerian        177040.0  177040.00  177040.0
Pakistan         28207.0   28207.00   28207.0
Palestinian      28145.0   28145.00   28145.0
Romania          28030.0   28030.00   28030.0
Russia           28143.0   28143.00   28143.0
Singaporean     162408.0  162408.00  162408.0
Sri Lanka        28108.0   28108.00   28108.0
Syria            28186.0   28186.00   28186.0
Taiwanese       169797.0  173415.00  177033.0
Thai            706343.5  706372.25  709087.0
Thailand        414178.0  609767.50  839175.0
Timor-Leste     124928.0  124928.00  124928.0
United Kingdom   28187.0   45261.50   62336.0
Vietnam          28057.0   28060.50   28233.0
Yemen            28095.0   28095.00   28095.0
burmese         196826.0  196827.50  501882.0
ไม่มีสัญชาติ     28155.0   28189.00   28223.0

In [12]:
missing_sex.groupby('province_of_onset').describe()

                       No.                                                     \
                     count           mean            std       min        25%
province_of_onset
กระบี่                31.0  152513.903226  172940.915430   73912.0   73921.50
กรุงเทพมหานคร      19606.0  475440.266806  211410.472306   27020.0  325081.25
กาญจนบุรี             66.0  512275.560606  179307.018971  124715.0  326376.75
กาฬสินธุ์            550.0  694090.878182  100570.982325  124654.0  705007.25
กำแพงเพชร             54.0  470169.481481  202354.605093  124646.0  304338.75
...                    ...            ...            ...       ...        ...
เพชรบุรี             658.0  180982.872340   91507.678167  133092.0  141781.25
เพชรบูรณ์            972.0  658937.264403   89381.199558  124886.0  633760.75
เลย                   35.0  565968.657143  172698.145637  258574.0  455496.00
แพร่                  46.0  487720.173913  171353.582841   42057.0  489185.75
แม่ฮ่องสอน             4.0  416370.250000  291965.500046   42139.0  255514.00


                        50%        75%       max
province_of_onset
กระบี่              73929.0   77013.00  628613.0
กรุงเทพมหานคร      464828.5  668486.50  839175.0
กาญจนบุรี          559565.0  668555.75  836415.0
กาฬสินธุ์          705144.5  748561.75  838087.0
กำแพงเพชร          444009.0  669697.00  836529.0
...                     ...        ...       ...
เพชรบุรี           141945.5  155581.75  710309.0
เพชรบูรณ์          673216.5  737278.25  838089.0
เลย                625889.0  651289.00  836476.0
แพร่               512850.5  534498.50  793424.0
แม่ฮ่องสอน         487324.5  648180.75  648693.0

[77 rows x 8 columns]

In [13]:
missing_sex.groupby(['province_of_onset','nationality']).describe() ## groupby หลาย column

                                  No.                                          \
                                count           mean            std       min
province_of_onset nationality
กระบี่            Thailand       25.0   74418.280000    1706.850743   73912.0
กรุงเทพมหานคร     Thailand     2735.0  246419.015356  178257.099047   27207.0
                  Burma           1.0   60725.000000            NaN   60725.0
                  Burmese       154.0  240054.000000  165463.451148  120567.0
                  Cambodian      53.0  129534.113208   27024.376188  120554.0
...                               ...            ...            ...       ...
เพชรบุรี          Indian          1.0  135871.000000            NaN  135871.0
                  burmese         1.0  501882.000000            NaN  501882.0
เพชรบูรณ์         Thailand      546.0  625724.014652   51407.080083  124886.0
เลย               Thailand       11.0  625890.272727       3.770700  625885.0
แพร่              Thailand       24.0  528826.875000   56268.335843  512840.0


                                     25%       50%        75%       max
province_of_onset nationality
กระบี่            Thailand      73920.00   73926.0   73933.00   80090.0
กรุงเทพมหานคร     Thailand      81029.50  177141.0  352608.50  839175.0
                  Burma         60725.00   60725.0   60725.00   60725.0
                  Burmese      124782.75  124954.0  451971.50  710812.0
                  Cambodian    120582.00  124670.0  124733.00  243952.0
...                                  ...       ...        ...       ...
เพชรบุรี          Indian       135871.00  135871.0  135871.00  135871.0
                  burmese      501882.00  501882.0  501882.00  501882.0
เพชรบูรณ์         Thailand     561948.25  633835.5  673222.75  740314.0
เลย               Thailand     625887.50  625890.0  625892.50  625897.0
แพร่              Thailand     512845.75  512851.5  512857.25  756703.0

[113 rows x 8 columns]

In [14]:
misssing_sex_no_burma = missing_sex[missing_sex['nationality']!='Burma']
misssing_sex_no_burma.groupby('risk').describe()

                                                      No.                 \
                                                    count           mean
risk
Cluster ชลบุรี                                       18.0    7507.055556
Cluster บางแค                                        54.0   27231.500000
Cluster ระยอง                                         7.0    6364.285714
Cluster สมุทรสาคร                                    85.0    7503.176471
State Quarantine                                      7.0  391877.142857
การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน   3388.0  382123.633707
ตรวจก่อนทำหัตถการ                                     3.0  368782.000000
ทัณฑสถาน/เรือนจำ                                   9468.0  184902.959125
บุคลากรด้านการแพทย์และสาธารณสุข                       8.0  574289.000000
ปอดอักเสบ (Pneumonia)                                15.0  441462.933333
ระบุไม่ได้                                         2063.0  668148.005817
ศูนย์กักกัน ผู้ต้องกัก                              113.0   28125.486726
สถานที่ทำงาน                                        536.0  220868.270522
สถานบันเทิง                                          20.0   36395.650000
สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้        1921.0  483345.627277
อยู่ระหว่างการสอบสวน                              12413.0  437591.160477
อื่นๆ                                             22987.0  560842.920259
ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว        92.0  512222.815217
ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต                 2.0  549333.500000

                                                                           \
                                                            std       min
risk
Cluster ชลบุรี                                         6.637436    7498.0
Cluster บางแค                                         15.732133   27205.0
Cluster ระยอง                                        201.569437    6268.0
Cluster สมุทรสาคร                                   1369.959012    6125.0
State Quarantine                                   25406.204986  382272.0
การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน  275077.834040   30813.0
ตรวจก่อนทำหัตถการ                                  65862.097985  292731.0
ทัณฑสถาน/เรือนจำ                                  150859.602654  101467.0
บุคลากรด้านการแพทย์และสาธารณสุข                   227256.548740   78543.0
ปอดอักเสบ (Pneumonia)                             145144.086413  175664.0
ระบุไม่ได้                                        205743.947922   60729.0
ศูนย์กักกัน ผู้ต้องกัก                                88.233367   27979.0
สถานที่ทำงาน                                      146180.417013  132805.0
สถานบันเทิง                                         4887.487400   31491.0
สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้       231738.268130   29965.0
อยู่ระหว่างการสอบสวน                              229187.658116    6544.0
อื่นๆ                                             162928.037556   32547.0
ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว     229511.939087   33955.0
ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต              72814.320793  497846.0

                                                                       \
                                                        25%       50%
risk
Cluster ชลบุรี                                      7502.25    7506.5
Cluster บางแค                                      27218.25   27231.5
Cluster ระยอง                                       6269.50    6271.0
Cluster สมุทรสาคร                                   6666.00    7658.0
State Quarantine                                  382273.50  382275.0
การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน  124928.75  343996.0
ตรวจก่อนทำหัตถการ                                 349769.00  406807.0
ทัณฑสถาน/เรือนจำ                                  103833.75  159210.5
บุคลากรด้านการแพทย์และสาธารณสุข                   570629.75  615698.5
ปอดอักเสบ (Pneumonia)                             398107.00  403915.0
ระบุไม่ได้                                        536198.50  834868.0
ศูนย์กักกัน ผู้ต้องกัก                             28050.00   28115.0
สถานที่ทำงาน                                      141765.75  155586.0
สถานบันเทิง                                        31537.25   34057.0
สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้       292720.00  495886.0
อยู่ระหว่างการสอบสวน                              306632.00  399108.0
อื่นๆ                                             421842.50  571125.0
ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว     482320.75  495473.5
ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต             523589.75  549333.5


                                                        75%       max
risk
Cluster ชลบุรี                                      7510.75    7525.0
Cluster บางแค                                      27244.75   27258.0
Cluster ระยอง                                       6331.00    6810.0
Cluster สมุทรสาคร                                   7679.00   13122.0
State Quarantine                                  382276.50  449493.0
การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน  733212.00  817961.0
ตรวจก่อนทำหัตถการ                                 406807.50  406808.0
ทัณฑสถาน/เรือนจำ                                  168944.25  839398.0
บุคลากรด้านการแพทย์และสาธารณสุข                   711621.50  797123.0
ปอดอักเสบ (Pneumonia)                             403958.00  756818.0
ระบุไม่ได้                                        836710.50  839305.0
ศูนย์กักกัน ผู้ต้องกัก                             28205.00   28271.0
สถานที่ทำงาน                                      194494.25  623310.0
สถานบันเทิง                                        42039.50   42136.0
สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้       615460.00  838333.0
อยู่ระหว่างการสอบสวน                              652896.00  833032.0
อื่นๆ                                             692154.50  837525.0
ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว     715241.25  715264.0
ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต             575077.25  600821.0

In [15]:
missing_sex.groupby('risk').describe()

                                                      No.                 \
                                                    count           mean
risk
Cluster ชลบุรี                                       18.0    7507.055556
Cluster บางแค                                        54.0   27231.500000
Cluster ระยอง                                         8.0    6453.250000
Cluster สมุทรสาคร                                  1501.0    5569.918055
State Quarantine                                      7.0  391877.142857
การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน   3413.0  380017.467038
ตรวจก่อนทำหัตถการ                                     3.0  368782.000000
ทัณฑสถาน/เรือนจำ                                   9468.0  184902.959125
บุคลากรด้านการแพทย์และสาธารณสุข                       8.0  574289.000000
ปอดอักเสบ (Pneumonia)                                15.0  441462.933333
ระบุไม่ได้                                         2064.0  667853.711725
ศูนย์กักกัน ผู้ต้องกัก                              280.0   28125.239286
สถานที่ทำงาน                                        536.0  220868.270522
สถานบันเทิง                                          20.0   36395.650000
สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้        1921.0  483345.627277
อยู่ระหว่างการสอบสวน                              12416.0  437493.239852
อื่นๆ                                             22990.0  560781.591649
ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว        92.0  512222.815217
ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต                 2.0  549333.500000

                                                                           \
                                                            std       min
risk
Cluster ชลบุรี                                         6.637436    7498.0
Cluster บางแค                                         15.732133   27205.0
Cluster ระยอง                                        313.277946    6268.0
Cluster สมุทรสาคร                                   1700.810832    4398.0
State Quarantine                                   25406.204986  382272.0
การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน  275164.782058   30813.0
ตรวจก่อนทำหัตถการ                                  65862.097985  292731.0
ทัณฑสถาน/เรือนจำ                                  150859.602654  101467.0
บุคลากรด้านการแพทย์และสาธารณสุข                   227256.548740   78543.0
ปอดอักเสบ (Pneumonia)                             145144.086413  175664.0
ระบุไม่ได้                                        206128.149870   60725.0
ศูนย์กักกัน ผู้ต้องกัก                                88.142418   27979.0
สถานที่ทำงาน                                      146180.417013  132805.0
สถานบันเทิง                                         4887.487400   31491.0
สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้       231738.268130   29965.0
อยู่ระหว่างการสอบสวน                              229247.206235    6544.0
อื่นๆ                                             163006.041679   32547.0
ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว     229511.939087   33955.0
ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต              72814.320793  497846.0

                                                                       \
                                                        25%       50%
risk
Cluster ชลบุรี                                      7502.25    7506.5
Cluster บางแค                                      27218.25   27231.5
Cluster ระยอง                                       6269.75    6271.5
Cluster สมุทรสาคร                                   4773.00    5170.0
State Quarantine                                  382273.50  382275.0
การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน  124910.00  343896.0
ตรวจก่อนทำหัตถการ                                 349769.00  406807.0
ทัณฑสถาน/เรือนจำ                                  103833.75  159210.5
บุคลากรด้านการแพทย์และสาธารณสุข                   570629.75  615698.5
ปอดอักเสบ (Pneumonia)                             398107.00  403915.0
ระบุไม่ได้                                        536197.75  834867.5
ศูนย์กักกัน ผู้ต้องกัก                             28048.75   28118.5
สถานที่ทำงาน                                      141765.75  155586.0
สถานบันเทิง                                        31537.25   34057.0
สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้       292720.00  495886.0
อยู่ระหว่างการสอบสวน                              306629.75  399106.5
อื่นๆ                                             421840.25  571123.5
ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว     482320.75  495473.5
ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต             523589.75  549333.5


                                                        75%       max
risk
Cluster ชลบุรี                                      7510.75    7525.0
Cluster บางแค                                      27244.75   27258.0
Cluster ระยอง                                       6495.00    7076.0
Cluster สมุทรสาคร                                   5575.00   13327.0
State Quarantine                                  382276.50  449493.0
การค้นหาผู้ป่วยเชิงรุกและค้นหาผู้ติดเชื้อในชุมชน  732676.00  817961.0
ตรวจก่อนทำหัตถการ                                 406807.50  406808.0
ทัณฑสถาน/เรือนจำ                                  168944.25  839398.0
บุคลากรด้านการแพทย์และสาธารณสุข                   711621.50  797123.0
ปอดอักเสบ (Pneumonia)                             403958.00  756818.0
ระบุไม่ได้                                        836710.25  839305.0
ศูนย์กักกัน ผู้ต้องกัก                             28205.25   28275.0
สถานที่ทำงาน                                      194494.25  623310.0
สถานบันเทิง                                        42039.50   42136.0
สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้       615460.00  838333.0
อยู่ระหว่างการสอบสวน                              652895.25  833032.0
อื่นๆ                                             692153.75  837525.0
ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว     715241.25  715264.0
ไปสถานที่แออัด เช่น งานแฟร์ คอนเสิร์ต             575077.25  600821.0

In [16]:
missing_sex[missing_sex['risk']=='Cluster สมุทรสาคร'].groupby('announce_date').count()

,No.,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
announce_date,,,,,,,,,,
20/12/2020,511,0,0,0,0,511,511,511,511,511
21/1/2021,29,29,0,0,0,29,29,29,29,0
21/12/2020,360,0,0,0,0,360,360,360,360,360
22/12/2020,397,0,0,0,0,397,397,397,397,397
23/1/2021,33,33,0,33,33,32,33,33,33,1
24/1/2021,1,1,0,1,1,1,1,1,1,1
25/12/2020,34,0,0,0,0,34,34,34,34,34
26/12/2020,30,0,0,0,0,30,30,30,30,30
27/12/2020,18,18,0,0,0,0,18,18,0,0
28/12/2020,14,0,0,0,0,14,14,14,14,14
3/1/2021,55,0,0,0,0,0,55,55,0,0
30/12/2020,3,0,0,0,0,1,3,3,0,0
31/12/2020,15,0,0,0,0,15,15,15,0,0
5/1/2021,1,1,0,0,0,0,1,1,1,1

สรุปสาเหตุที่ข้อมูล sex เป็น missing:
ข้อมูลเพศที่สูญหาย (missing) ส่วนใหญ่เกิดจากกรณี Cluster สมุทรสาคร ในช่วงปลายเดือนธันวาคม 2020 ซึ่งเป็นการตรวจคัดกรองเชิงรุกกับกลุ่มแรงงานต่างด้าวจำนวนมากในเวลาอันสั้น ในช่วงเวลาดังกล่าวเน้นการบันทึกข้อมูลเพื่อควบคุมโรคอย่างเร่งด่วน ทำให้การลงประวัติส่วนบุคคล (เช่น เพศ และ อายุ) ไม่สมบูรณ์และถูกเว้นไว้เป็นค่าว่าง